pool:
  name: Hosted Windows 2019 with VS2019
  demands: npm

steps:
- task: Npm@1
  displayName: 'NPM Install'
  inputs:
    workingDir: source/Web/Frontend
    verbose: false

- task: Npm@1
  displayName: 'NPM Install Angular CLI'
  inputs:
    command: custom
    workingDir: source/Web/Frontend
    verbose: false
    customCommand: 'install -g @angular/cli'

- task: Npm@1
  displayName: 'NPM Run Production'
  inputs:
    command: custom
    workingDir: source/Web/Frontend
    verbose: false
    customCommand: 'run production'

- task: DotNetCoreCLI@2
  displayName: '.NET Publish'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/*.Web.csproj'
    arguments: '--configuration release --output $(build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: CopyFiles@2
  displayName: 'Copy Angular Dist'
  inputs:
    SourceFolder: source/Web/Frontend/dist
    TargetFolder: '$(build.ArtifactStagingDirectory)/Web/Frontend/dist'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    ArtifactName: publish
